{{- if and .Values.community false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectName }}-cm
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
data:
  baseUrl: {{ .Values.opsManagerUrl }}
  projectName: {{ .Values.projectName }}
  orgId: {{ .Values.orgId }}
  {{- end }} # if and .Values.community false