apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectName }}-cm
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
data:
  baseUrl: {{ .Values.opsManagerUrl }}
  projectName: {{ .Values.projectName }}
  orgId: "6a0c9cd2da71140ad69b1e48"