apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectName }}-cm
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/resource-policy: keep
data:
  baseUrl: http://om.lab
  projectName: {{ .Values.projectName }}
  orgId: "6a0c9cd2da71140ad69b1e48"