apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.projectName }}-organization-secret
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/resource-policy: keep
stringData:
  publicKey: {{ .Values.omPublicKey }}
  privateKey: {{ .Values.omPrivateKey }}