apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}-self-signed-issuer
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-ca
  namespace: {{ .Values.certManagerNamespace }}
spec:
  isCA: true
  commonName: mongodb-ca
  secretName: tls-ca-secret
  duration: 87600h  # 10 years
  renewBefore: 8760h  # 1 year
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.name }}-self-signed-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}-tls-ca-issuer
spec:
  ca:
    secretName: tls-ca-secret

---

apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ .Values.name }}-mdb-tls-ca-configmap
  namespace: {{ .Values.namespace }}
spec:
  sources:
    - secret:
        name: "tls-ca-secret"
        key: "tls.crt"
  target:
    configMap:
      key: "ca-pem"
    # trust-manager will automatically create mdb-tls-ca-configmap in all matching namespaces
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Values.namespace | quote }}

---

# Cluster TLS certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.name }}-cert
  duration: 8760h    # 1 year
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.{{ .Values.name }}-svc.mongodb.svc.cluster.local"
  issuerRef:
    name: {{ .Values.name }}-tls-ca-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-search-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.name }}-search-cert
  duration: 8760h    # 1 year
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.{{ .Values.name }}-svc.mongodb.svc.cluster.local"
  issuerRef:
    name: {{ .Values.name }}-tls-ca-issuer
    kind: ClusterIssuer

---

# Create a certificate for use by envoy load balancer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-search-lb-0-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.name }}-search-lb-0-cert
  duration: 8760h    # 1 year
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
  dnsNames:
    - "*.{{ .Values.name }}-svc.mongodb.svc.cluster.local"
  issuerRef:
    name: {{ .Values.name }}-tls-ca-issuer
    kind: ClusterIssuer

---

# Create client certificate for envoy load balancer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-search-lb-0-client-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.name }}-search-lb-0-client-cert
  duration: 8760h    # 1 year
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - client auth
  dnsNames:
    - "*.{{ .Values.name }}-svc.mongodb.svc.cluster.local"
  issuerRef:
    name: {{ .Values.name }}-tls-ca-issuer
    kind: ClusterIssuer