{{- if and (eq .Values.authEnabled true) .Values.community false }}
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: root
  namespace: {{ .Release.Namespace }}
spec:
  username: root
  db: admin
  mongodbResourceRef:
    name: {{ .Values.name }}
  passwordSecretKeyRef:
    name: {{ .Values.name }}-root-password
    key: password
  roles:
  - name: root
    db: admin

---

apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: search-sync-source
  namespace: {{ .Release.Namespace }}
spec:
  username: search-sync-source
  db: admin
  mongodbResourceRef:
    name: {{ .Values.name }}
  passwordSecretKeyRef:
    name: {{ .Values.name }}-search-sync-source-password
    key: password
  roles:
  - name: searchCoordinator
    db: admin

{{- end }}

{{- if .Values.authEnabled }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-root-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.rootPassword }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-search-sync-source-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.searchSyncUserPassword }}
{{- end }} # if .Values.authEnabled