{{- if eq .Values.authEnabled true }}
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: root
  namespace: {{ .Release.Namespace }}
spec:
  username: root
  db: admin
  mongodbResourceRef:
    name: {{ .Values.name }}
  passwordSecretKeyRef:
    name: root-password
    key: password
  roles:
  - name: root
    db: admin

---

apiVersion: v1
kind: Secret
metadata:
  name: root-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.rootPassword }}

---

apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: search-sync-source
  namespace: {{ .Release.Namespace }}
spec:
  username: search-sync-source
  db: admin
  mongodbResourceRef:
    name: {{ .Values.name }}
  passwordSecretKeyRef:
    name: {{ .Values.name }}-search-sync-source-password
    key: password
  roles:
  - name: searchCoordinator
    db: admin

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-search-sync-source-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.searchSyncUserPassword }}

{{- end }}