omPublicKey: "your-om-public-key"
omPrivateKey: "your-om-private-key"

# Tools
launchClientPod: false

# Authentication
authEnabled: true
rootPassword: "password"
searchSyncUserPassword: "password"

name: "my-replica-set"
namespace: "default"
projectName: "my-project"

# Cluster topology
members: 3
type: "replicaSet"

# Sharded Cluster Settings
shards: 2
mongosCount: 2
configServerCount: 1

# Search Settings
searchEnabled: true
searchReplicas: 2
searchLoadBalancerReplicas: 1

# TLS settings
tlsEnabled: false
certManagerNamespace: cert-manager