# General info
omPublicKey: "your-om-public-key"
omPrivateKey: "your-om-private-key"
opsManagerUrl: "https://cloud.mongodb.com" # Leave this value as-is if using cloud manager, otherwise set it to your Ops Manager URL
name: "my-replica-set" # name of your cluster
projectName: "my-project"

# Tools
launchClientPod: false

# Authentication
authEnabled: true
rootPassword: "password"
searchSyncUserPassword: "password"

# Cluster topology
members: 3 # This will be the number of members in your replica set OR members per shard in a sharded cluster
type: "replicaSet" # "replicaSet" or "shardedCluster"

# Sharded Cluster Settings
shards: 2
mongosCount: 2
configServerCount: 1

# Search Settings
searchEnabled: true
searchReplicas: 2
searchLoadBalancerReplicas: 1

# TLS settings
tlsEnabled: false
certManagerNamespace: cert-manager # Namespace where cert-manager is installed